# Generated by Django 2.1.3 on 2018-11-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='_id',
        ),
    ]
